POST http://localhost:3000/api/post/new
Content-Type: application/json

{
    "content": "new aga"
}

###

GET http://localhost:3000/api/post

###

GET http://localhost:3000/api/post/654e9726582cea9fc0947f9c

